apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: rlsmailandstuff
spec:
  build:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "71a4023e-1230-4c09-84e2-cb587c433dad"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET